version: '3.4'

services:
  db:
    image: postgres
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: qwe123
    ports:
      - '54321:5432'
    volumes:
      - ../2. Init Database:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 4G

  redis:
    image: docker.io/bitnami/redis:7.0
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL
    ports:
      - '6379:6379'
    volumes:
      - 'redis_data:/bitnami/redis/data'
    depends_on:
      - db

  rabbitmq3:
    image: rabbitmq:3.8-management-alpine
    ports:
      # AMQP protocol port
      - '5672:5672'
      # HTTP management UI
      - '15672:15672'
    depends_on:
      - redis

  webapi:
    build:
      context: .
      dockerfile: TestPet/Dockerfile
    ports:
      - "5001:8080"
    depends_on:
      - rabbitmq3

  frontend:
    build:
      context: animeShopUI
      dockerfile: Dockerfile
    ports:
      - "80:4200"

volumes:
  redis_data:
    driver: local
